//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACDetail
    {
        public long ID { get; set; }
        public string Ac { get; set; }
        public string Cbsdtls { get; set; }
        public string JoinHldrs { get; set; }
        public int actype { get; set; }
    }
}
