//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSecPolicy
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PwdExpiryDays { get; set; }
        public int MinPwdLength { get; set; }
        public int MaxPwdLength { get; set; }
        public bool AlphanumericMandatory { get; set; }
        public bool SpecialCharMandatory { get; set; }
        public int InvalidAttemptsAllowed { get; set; }
        public int DeactivationDays { get; set; }
    }
}
