//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string PresentingBankRouteNo { get; set; }
        public int GridId { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CBSFixAccountNo { get; set; }
        public Nullable<bool> CxfUseNetworkDrive { get; set; }
        public string CxfPortNo { get; set; }
        public Nullable<bool> CxfIsSFTP { get; set; }
        public string CxfServerName { get; set; }
        public string CxfLoginId { get; set; }
        public string CxfPassword { get; set; }
        public string CxfSubDirectory { get; set; }
        public Nullable<byte> CxfFtpSDKType { get; set; }
        public string CxfWinScpSshHostKeyFingerprint { get; set; }
        public string CxfNetworkDrivePath { get; set; }
        public Nullable<bool> CxfApplyDefaultDS { get; set; }
        public string CxfCertificatePath { get; set; }
        public string CxfCertificatePassword { get; set; }
        public Nullable<bool> BrfUseNetworkDrive { get; set; }
        public string BrfPortNo { get; set; }
        public Nullable<bool> BrfIsSFTP { get; set; }
        public string BrfServerName { get; set; }
        public string BrfLoginId { get; set; }
        public string BrfPassword { get; set; }
        public string BrfSubDirectory { get; set; }
        public Nullable<byte> BrfFtpSDKType { get; set; }
        public string BrfWinScpSshHostKeyFingerprint { get; set; }
        public Nullable<bool> RrfUseNetworkDrive { get; set; }
        public string RrfPortNo { get; set; }
        public Nullable<bool> RrfIsSFTP { get; set; }
        public string RrfServerName { get; set; }
        public string RrfLoginId { get; set; }
        public string RrfPassword { get; set; }
        public string RrfSubDirectory { get; set; }
        public Nullable<byte> RrfFtpSDKType { get; set; }
        public string RrfWinScpSshHostKeyFingerprint { get; set; }
        public Nullable<bool> CxfIsActive { get; set; }
        public Nullable<bool> BrfIsActive { get; set; }
        public Nullable<bool> RrfIsActive { get; set; }
        public Nullable<bool> CxfRejectHomeClearingCheques { get; set; }
        public Nullable<bool> CxfMarkHomeClearingAsTransfer { get; set; }
        public string CxfHomeClearingBankCodes { get; set; }
        public string BrfNetworkDrivePath { get; set; }
        public string RrfNetworkDrivePath { get; set; }
        public string Grid { get; set; }
    }
}
