//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardSingleDomainDashBoard
    {
        public System.DateTime ProcessDate { get; set; }
        public int DomainId { get; set; }
        public int SlipAmtTotal { get; set; }
        public int SlipAmtPending { get; set; }
        public int SlipAmtComplete { get; set; }
        public int ChequeAmtTotal { get; set; }
        public int ChequeAmtD1Pending { get; set; }
        public int ChequeAmtD2Pending { get; set; }
        public int ChequeAmtComplete { get; set; }
        public int ChequeDateTotal { get; set; }
        public int ChequeDateD1Pending { get; set; }
        public int ChequeDateD2Pending { get; set; }
        public int ChequeDateComplete { get; set; }
        public int L1VerificationSlipPending { get; set; }
        public int L1VerificationSlipAccepted { get; set; }
        public int L1VerificationSlipRejected { get; set; }
        public int L1VerificationChequePending { get; set; }
        public int L1VerificationChequeAccepted { get; set; }
        public int L1VerificationChequeRejected { get; set; }
        public int L2VerificationSlipPending { get; set; }
        public int L2VerificationSlipAccepted { get; set; }
        public int L2VerificationSlipHold { get; set; }
        public int L2VerificationSlipRejected { get; set; }
        public int L2VerificationChequePending { get; set; }
        public int L2VerificationChequeAccepted { get; set; }
        public int L2VerificationChequeHold { get; set; }
        public int L2VerificationChequeRejected { get; set; }
        public int L3VerificationSlipPending { get; set; }
        public int L3VerificationSlipAccepted { get; set; }
        public int L3VerificationSlipHold { get; set; }
        public int L3VerificationSlipRejected { get; set; }
        public int L3VerificationChequePending { get; set; }
        public int L3VerificationChequeAccepted { get; set; }
        public int L3VerificationChequeHold { get; set; }
        public int L3VerificationChequeRejected { get; set; }
        public int PresentationPending { get; set; }
        public int PresentationPresented { get; set; }
        public int PresentationRejected { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> SlipAccountTotal { get; set; }
        public Nullable<int> SlipAccountD1Pending { get; set; }
        public Nullable<int> SlipAccountD2Pending { get; set; }
        public Nullable<int> SlipAccountComplete { get; set; }
        public int L1VerificationTotalSlips { get; set; }
        public int L1VerificationTotalCheques { get; set; }
        public int L2VerificationTotalSlips { get; set; }
        public int L2VerificationTotalCheques { get; set; }
        public int L3VerificationTotalSlips { get; set; }
        public int L3VerificationTotalCheques { get; set; }
    }
}
