//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardDomainDashBoard_V2
    {
        public System.DateTime ProcessDate { get; set; }
        public int CustomerId { get; set; }
        public int DomainId { get; set; }
        public string scanNodeDesc { get; set; }
        public int cntSlips { get; set; }
        public int cntchqs { get; set; }
        public int cntslipamtde { get; set; }
        public int cntchqamtde { get; set; }
        public int cntchqmicr { get; set; }
        public int cntchqdatede { get; set; }
        public int cntslipaccountde { get; set; }
        public int cntchqaccountde { get; set; }
        public int cntL1VerSC { get; set; }
        public int cntL1VerC { get; set; }
        public int cntL2VerSC { get; set; }
        public int cntL2VerC { get; set; }
        public int cntL3VerSC { get; set; }
        public int cntL3VerC { get; set; }
        public int cntDiscrepant { get; set; }
        public int cntChireject { get; set; }
        public int cntP2f { get; set; }
        public int cntReadyforBundling { get; set; }
        public int cntResrecvd { get; set; }
        public int cntOackrecvd { get; set; }
        public string CustomerName { get; set; }
        public string ClearingType { get; set; }
        public Nullable<int> cntTrfChqs { get; set; }
        public Nullable<int> cntTrfChqsL1 { get; set; }
        public Nullable<int> cntTrfChqsL2 { get; set; }
        public Nullable<int> cntTrfChqsL3 { get; set; }
        public Nullable<int> HoldSlipsL2 { get; set; }
        public Nullable<int> HoldSlipsL3 { get; set; }
        public Nullable<int> cntTrfDiscrepant { get; set; }
        public Nullable<int> cntChiReturn { get; set; }
    }
}
