//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODs
    {
        public int ID { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public string Status { get; set; }
        public string ClearingType { get; set; }
        public Nullable<System.DateTime> SODRunOn { get; set; }
        public Nullable<System.DateTime> EODRunOn { get; set; }
        public int SODBy_ID { get; set; }
        public Nullable<int> EDOBy_ID { get; set; }
        public string ProcessTypes { get; set; }
        public System.DateTime PostDated { get; set; }
        public System.DateTime StaleDated { get; set; }
    }
}
