//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public int ID { get; set; }
        public string ClearingType { get; set; }
        public bool DEBySnippet { get; set; }
        public bool QCEnabled { get; set; }
        public bool CaptureSlipAccount { get; set; }
        public bool CaptureSlipAmount { get; set; }
        public bool CaptureChqAmount { get; set; }
        public bool CaptureChqDate { get; set; }
        public bool CaptureChqCrdAccount { get; set; }
        public bool CaptureChqDbtAccount { get; set; }
        public bool CaptureChqPayeeName { get; set; }
        public bool CaptureChqDraweeName { get; set; }
        public bool AutoCaptureSlipAccount { get; set; }
        public bool AutoCaptureSlipAmount { get; set; }
        public bool AutoCaptureChqAmount { get; set; }
        public bool AutoCaptureChqDate { get; set; }
        public bool AutoCaptureChqCrdAccount { get; set; }
        public bool AutoCaptureChqDbtAccount { get; set; }
        public bool AutoCaptureChqPayeeName { get; set; }
        public bool AutoCaptureChqDraweeName { get; set; }
        public bool AutoUVDetection { get; set; }
        public bool AutoIRDetection { get; set; }
        public bool AutoWatermarkDetection { get; set; }
        public bool AutoVoidDetection { get; set; }
        public bool AutoMicroletteringDetection { get; set; }
        public bool AutoCodelineDecode { get; set; }
        public bool CentralizedIQAEnabled { get; set; }
        public bool DSEnabled { get; set; }
        public bool DisplayCustNameInDE { get; set; }
        public bool FetchAllPayeeNames { get; set; }
        public bool Reverification { get; set; }
        public Nullable<double> ReverificationFromAmt { get; set; }
        public Nullable<double> ReverificationToAmt { get; set; }
        public bool SANCompulsory { get; set; }
        public bool RejectReasonPopup { get; set; }
        public bool RejectInvalidDate { get; set; }
        public Nullable<int> StaleDateDays { get; set; }
        public bool NRE { get; set; }
        public Nullable<int> MaxRecordsPerFile { get; set; }
        public int AccLenthFrom { get; set; }
        public int AccLenthTo { get; set; }
        public bool ShowMICRInQC { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public int Domain_ID { get; set; }
        public Nullable<bool> DefaultIQA { get; set; }
        public Nullable<bool> FetchAccNoFromCBS { get; set; }
        public Nullable<bool> AccountDualEntry { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
