//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_CustomerMaster
    {
        public long ID { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Is_Our_Bank_Customer { get; set; }
        public string Customer_Hierarchy_Required { get; set; }
        public string Customer_Divsion_Required { get; set; }
        public string Customer_s_Subcustomer_Required { get; set; }
        public string Customer_s_Subcustomer_Mandatory { get; set; }
        public string Customer_Consolidation_Pooling_Required { get; set; }
        public string Customer_Details_Entered_By { get; set; }
        public string Customer_Details_Entered_On { get; set; }
        public string Customer_Details_Authorized_by { get; set; }
        public string Customer_Details_Authorized_on { get; set; }
        public string Customer_Details_Last_Modified_By { get; set; }
        public string Customer_Details_Last_Modified_On { get; set; }
        public string CUSTOMER_WEBCMS_CHEQUE_FORMAT { get; set; }
        public string CUSTOMER_WEBCMS_CASH_FORMAT { get; set; }
        public string CUSTOMER_FORMAT_CODE { get; set; }
        public string CUSTOMER_TBMS_DIVISIONWISE_CHARGES_REQUIRED { get; set; }
        public string CUSTOMER_WEBCMS_BULK_FORMAT { get; set; }
        public string CUSTOMER_DATA_STORE_REQUIRED { get; set; }
    }
}
