//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxfFileStatu
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public Nullable<int> FileId { get; set; }
        public string FileName { get; set; }
        public string CibfName { get; set; }
        public Nullable<int> Status { get; set; }
        public string ClearingType { get; set; }
        public string DestinationServer { get; set; }
        public Nullable<byte> RESFileCount { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> OACKCount { get; set; }
        public Nullable<int> RejectCount { get; set; }
        public Nullable<decimal> FileTotalAmount { get; set; }
        public Nullable<System.DateTime> CreationTimeStamp { get; set; }
        public Nullable<System.DateTime> UploadTimeStamp { get; set; }
        public Nullable<System.DateTime> RESTimeStamp { get; set; }
        public Nullable<System.DateTime> OACKTimeStamp { get; set; }
    }
}
