//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWImageDtl
    {
        public int ID { get; set; }
        public int FileSeqNo { get; set; }
        public string SideIndicator { get; set; }
        public string ImgFormat { get; set; }
        public string FileName { get; set; }
        public string ImgDataOffset { get; set; }
        public string ImgDataLength { get; set; }
        public int FetchStatus { get; set; }
        public Nullable<int> File_ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual IWFileHDR IWFileHDR { get; set; }
    }
}
