//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiSessionDefinitionMaster
    {
        public string SessionNo { get; set; }
        public string Description { get; set; }
        public string ValidMon { get; set; }
        public string ValidTue { get; set; }
        public string ValidWed { get; set; }
        public string ValidThu { get; set; }
        public string ValidFri { get; set; }
        public string ValidSat { get; set; }
        public string ValidSun { get; set; }
        public string OpenReceivingTime { get; set; }
        public string OpenReceivingOffSetDays { get; set; }
        public string CloseReceivingTime { get; set; }
        public string CalenderCode { get; set; }
        public string SessionOperationModeCode { get; set; }
        public string CurrencyCode { get; set; }
    }
}
