//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clearinghouse
    {
        public Clearinghouse()
        {
            this.ClearingHouseInterfaces = new HashSet<ClearingHouseInterface>();
        }
    
        public string CH_ROUTING_NBR { get; set; }
    
        public virtual ICollection<ClearingHouseInterface> ClearingHouseInterfaces { get; set; }
    }
}
