//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_SubCustomerMaster
    {
        public long ID { get; set; }
        public string SUBCUST_CUST_CODE { get; set; }
        public string SUBCUST_SUB_CUST_CODE { get; set; }
        public string SUBCUST_SUB_CUST_NAME { get; set; }
        public string SUBCUST_LOC_CODE { get; set; }
        public string SUBCUST_CODE_GIVEN_BY_CUST { get; set; }
        public string SUBCUST_BELONGS_TO_DIVN { get; set; }
        public string SUBCUST_BELONGS_TO_HIER { get; set; }
        public string SUBCUST_STATUS_FLAG { get; set; }
        public string SUBCUST_ENTD_BY { get; set; }
        public Nullable<System.DateTime> SUBCUST_ENTD_ON { get; set; }
        public string SUBCUST_AUTH_BY { get; set; }
        public Nullable<System.DateTime> SUBCUST_AUTH_ON { get; set; }
        public string SUBCUST_LAST_MOD_BY { get; set; }
        public Nullable<System.DateTime> SUBCUST_LAST_MOD_ON { get; set; }
        public string SUBCUST_LAST_USED_OPT { get; set; }
    }
}
