//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_CustomerProductAdditionaInfo
    {
        public long ID { get; set; }
        public string cust_code { get; set; }
        public string prod_code { get; set; }
        public Nullable<System.DateTime> customer_prod_eff_date { get; set; }
        public string customer_additional_info_dtl_sl { get; set; }
        public string customer_production_deposit_inst_level { get; set; }
        public string customer_legend { get; set; }
        public string customer_master_serial { get; set; }
        public string CUSPAI_DATA_SIZE { get; set; }
        public string customer_additional_info_dtl_sl1 { get; set; }
        public string customer_addition_datatype { get; set; }
        public string customer_additional_Mandatore { get; set; }
        public string customer_additional_data_format { get; set; }
        public string customer_additional_mask_charter { get; set; }
        public string customer_addition_value_type { get; set; }
    }
}
