//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitAccountDump
    {
        public System.DateTime ProcessingDate { get; set; }
        public string SenderMICRCode { get; set; }
        public string DbtAccNo { get; set; }
        public string SerialNo { get; set; }
        public decimal Amount { get; set; }
        public string PRESENTMENTDATE { get; set; }
        public string TransCode { get; set; }
        public string INSTRPREFIX { get; set; }
        public string INSTRISSBR { get; set; }
        public string INSTRISSDT { get; set; }
        public string INSTRBFR { get; set; }
        public string DIN { get; set; }
        public string PayorBankRoutNo { get; set; }
        public string RECEIVERBRANCHNO { get; set; }
        public string PayeeName { get; set; }
    }
}
