//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_OurBranchMaster
    {
        public long ID { get; set; }
        public Nullable<int> OUR_BRANCH_CODE { get; set; }
        public string OUR_BRANCH_NAME { get; set; }
        public string OUR_BRANCH_LOCATION_CODE { get; set; }
        public Nullable<int> OUR_BRANCH_CMS_ROLE { get; set; }
        public string OUR_BRANCH_STATUS_FLAG { get; set; }
        public string OUR_BRANCH_ENTD_BY { get; set; }
        public Nullable<System.DateTime> OUR_BRANCH_ENTD_ON { get; set; }
        public string OUR_BRANCH_AUTH_BY { get; set; }
        public Nullable<System.DateTime> OUR_BRANCH_AUTH_ON { get; set; }
        public Nullable<int> OUR_BRANCH_MICR_CODE { get; set; }
        public string OUR_BRANCH_LAST_USED_OPT { get; set; }
        public string OUR_BRANCH_CTS_ENABLED { get; set; }
    }
}
