//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxfResponse
    {
        public long Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FileName { get; set; }
        public string ItemSeqNo { get; set; }
        public string PayorBankRouteNo { get; set; }
        public string Amount { get; set; }
        public string AccountNo { get; set; }
        public string SerialNo { get; set; }
        public string TransCode { get; set; }
        public string PresentingBankRouteNo { get; set; }
        public Nullable<System.DateTime> PresentmentDate { get; set; }
        public string CycleNo { get; set; }
        public Nullable<int> RejectReason { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
