//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadedFileSummary
    {
        public int ID { get; set; }
        public string CTSFILE_NAME { get; set; }
        public string SOURCESERVER { get; set; }
        public Nullable<System.DateTime> DOWNLOADEDDATETIME { get; set; }
        public Nullable<System.DateTime> PROCESSEDDATETIME { get; set; }
        public Nullable<int> PROCESSED { get; set; }
        public Nullable<int> TOTALCOUNT { get; set; }
        public Nullable<System.DateTime> SODDATE { get; set; }
    }
}
