//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWActivityLog
    {
        public int ID { get; set; }
        public Nullable<int> IWMainTrID { get; set; }
        public Nullable<int> IWImgTrID { get; set; }
        public string LogLevel { get; set; }
        public string Activity { get; set; }
        public Nullable<int> OpsStatus { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string LoginID { get; set; }
        public string RejectDesc { get; set; }
        public string Comments { get; set; }
        public string Processingdate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string PositiveDate { get; set; }
        public Nullable<decimal> PositiveAmount { get; set; }
        public string PositivePayee { get; set; }
    }
}
