//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWPayeeTmpProcess
    {
        public long ID { get; set; }
        public Nullable<int> MiscStatus { get; set; }
        public int OpsStatus { get; set; }
        public string XMLPayee { get; set; }
        public string EntryPayee { get; set; }
        public Nullable<decimal> XMLAmount { get; set; }
        public string EntrySerialNo { get; set; }
        public string EntryPayorBankRoutNo { get; set; }
        public string EntrySAN { get; set; }
        public string EntryTransCode { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string DbtAccountNo { get; set; }
        public string Date { get; set; }
        public string RejectReason { get; set; }
        public string RejectDescription { get; set; }
        public Nullable<int> PayeeDEBy { get; set; }
        public Nullable<int> L1By { get; set; }
        public Nullable<int> L2By { get; set; }
        public Nullable<int> L3By { get; set; }
        public string CBSClientAccountDtls { get; set; }
        public string CBSJointHoldersName { get; set; }
        public string FrontGreyImagePath { get; set; }
        public string FrontTiffImagePath { get; set; }
        public string BackTiffImagePath { get; set; }
        public string Snippet { get; set; }
        public Nullable<long> File_ID { get; set; }
        public Nullable<int> FileSeqNo { get; set; }
        public string ClearingType { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public string PresentingBankRoutNo { get; set; }
        public string DocType { get; set; }
        public string XMLMICRRepairFlags { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> L1Status { get; set; }
        public Nullable<int> L2Status { get; set; }
        public Nullable<int> L3Status { get; set; }
        public string L1RejectReason { get; set; }
        public string L2RejectReason { get; set; }
        public string L3RejectReason { get; set; }
    }
}
