//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuDescrp { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
