//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwCHIFileStatu
    {
        public int ID { get; set; }
        public int CTSFILE_ID { get; set; }
        public string CTSFILE_NAME { get; set; }
        public Nullable<int> FTP_STATUS { get; set; }
        public Nullable<int> DONE_STATUS { get; set; }
        public string CLEARINGTYPE { get; set; }
        public Nullable<int> REJECTCOUNT { get; set; }
        public string CIBFNAME { get; set; }
        public string DESTINATIONSERVER { get; set; }
        public System.DateTime PROCESSDATE { get; set; }
        public Nullable<int> TOTALITEMS { get; set; }
        public Nullable<int> ACCEPTEDITEMS { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public string SESSIONID_SESSION_NBR { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
