//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupMaster
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDescrp { get; set; }
        public Nullable<int> GroupCreatedBy { get; set; }
        public Nullable<System.DateTime> GroupCreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
