//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaster
    {
        public int Id { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string IFSCode { get; set; }
        public string MICRCode { get; set; }
        public int OwDomainId { get; set; }
        public Nullable<int> IwDomainId { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
