//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ProductMaster
    {
        public long ID { get; set; }
        public string Product_Code { get; set; }
        public string Product_Description { get; set; }
        public string Product_Type { get; set; }
        public string Product_Usage { get; set; }
        public string Product_covers_Our_Location { get; set; }
        public string Product_covering_corr_location { get; set; }
        public string Product_covering_Out_Location { get; set; }
        public string Product_PDC_Allowed { get; set; }
        public string Product_Cash_Allowed { get; set; }
        public string Product_Entered_by { get; set; }
        public Nullable<System.DateTime> Product_Entered_On { get; set; }
        public string Product_Authorized_by { get; set; }
        public Nullable<System.DateTime> Product_Authorized_On { get; set; }
        public string Product_Collection_Allowed { get; set; }
        public string Product_Speed_Product { get; set; }
    }
}
