//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCRICR
    {
        public long MainTransID { get; set; }
        public string MChqNo { get; set; }
        public string MChqSortCode { get; set; }
        public string MSAN { get; set; }
        public string MTrCode { get; set; }
        public string NChqNo { get; set; }
        public string NChqSortCode { get; set; }
        public string NSAN { get; set; }
        public string NTrCode { get; set; }
        public string IChqNo { get; set; }
        public string IChqSortCode { get; set; }
        public string ISAN { get; set; }
        public string ITrCode { get; set; }
        public string MICRRepairStatus { get; set; }
        public string MICRFlag { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string MICRString { get; set; }
        public string NIString { get; set; }
        public string ParaString { get; set; }
        public string ClearingType { get; set; }
    }
}
