//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanningNodeMaster
    {
        public int Id { get; set; }
        public int Organizationid { get; set; }
        public int CustomerId { get; set; }
        public int DomainId { get; set; }
        public string MACIP { get; set; }
        public string IPAddress { get; set; }
        public string ComputerName { get; set; }
        public string Location { get; set; }
        public string TruncatingRouteNo { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
