//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Customers = new HashSet<Customer>();
            this.BankBranches = new HashSet<BankBranches>();
        }
    
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL_ZIP_CODE { get; set; }
        public string CLEARING_STATUS_CODE { get; set; }
        public string SERVICE_BRANCH_ROUTING_NBR { get; set; }
        public string DESIGNATED_BRANCH_ROUTING_NBR { get; set; }
        public string CBS_ENABLED { get; set; }
        public string NOTE { get; set; }
        public string CHI_CC_ROUTING_NBR { get; set; }
    
        public virtual ClearingHouseInterface ClearingHouseInterface { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<BankBranches> BankBranches { get; set; }
    }
}
