//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordHistory
    {
        public int ID { get; set; }
        public System.DateTime PassworChangeDate { get; set; }
        public string Password { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> PasswordChangedBy_ID { get; set; }
    }
}
