//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranches
    {
        public BankBranches()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public string BankBranchCode { get; set; }
        public string BankBranchName { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL_ZIP_CODE { get; set; }
        public string BRANCH_NUMBER { get; set; }
        public string NOTE { get; set; }
        public string Bank_BankCode { get; set; }
    
        public virtual Bank Banks { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
