//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMaster1
    {
        public int Id { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public int DomainId { get; set; }
        public int ScanningNodeId { get; set; }
        public string BranchCode { get; set; }
        public int BatchNo { get; set; }
        public Nullable<int> ChequeCount { get; set; }
        public Nullable<decimal> TotalChequeAmount { get; set; }
        public byte CaptureSource { get; set; }
        public byte Status { get; set; }
        public string LockUserId { get; set; }
        public Nullable<byte> MICRSetting { get; set; }
        public Nullable<byte> SlipChequeSettings { get; set; }
        public Nullable<byte> ChequeAmountSettings { get; set; }
        public Nullable<byte> ChequeDateSettings { get; set; }
        public Nullable<byte> ChequeAccountNoSettings { get; set; }
        public Nullable<byte> SlipAccountNoSettings { get; set; }
        public Nullable<byte> SlipAmountSettings { get; set; }
        public string ClearingType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<byte> ScanningType { get; set; }
        public Nullable<System.DateTime> ScanCutOffDateTime { get; set; }
        public Nullable<byte> ScannedAfterCutOff { get; set; }
        public string Branch_DE_Status { get; set; }
        public Nullable<long> Lock_UserId { get; set; }
    }
}
