//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_CustomerProductLocationMaster
    {
        public long ID { get; set; }
        public string Customer_Code { get; set; }
        public string Product_Code { get; set; }
        public string Location_Code { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public string Status_Flag { get; set; }
        public string Entered_By { get; set; }
        public Nullable<System.DateTime> Entered_On { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.DateTime> Authorized_On { get; set; }
        public string Last_Used_Option { get; set; }
        public string Group_or_Location { get; set; }
        public string Cash_Facility_all_Branches { get; set; }
    }
}
