//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_CustomerProductMaster
    {
        public long ID { get; set; }
        public string customer_code { get; set; }
        public string customer_product_code { get; set; }
        public Nullable<System.DateTime> customer_prod_effective_date { get; set; }
        public string customer_prod_charges_recovered_immed { get; set; }
        public Nullable<System.DateTime> customer_prod_service_commencement { get; set; }
        public Nullable<System.DateTime> customer_prd_expiry { get; set; }
        public string cutomer_prod_day_one_defn { get; set; }
        public string cusprd_our_bank_arrangment { get; set; }
        public string customer_prd_corr_definition { get; set; }
        public string customer_prod_corr_loc_arrangmemt { get; set; }
        public string customer_prod_out_definition { get; set; }
        public string customer_prod_out_loc_arrangment { get; set; }
        public string customer_prod_dvision_req { get; set; }
        public string customer_prod_dvision_mandatory { get; set; }
        public string cutomer_division_entry_level { get; set; }
        public string customer_prod_hier_req { get; set; }
        public string customer_prod_hier_mandaory { get; set; }
        public string customer_inst_dtls_req { get; set; }
        public string customer_prod_inst_dtls_mand { get; set; }
        public string customer_product_drawer_req { get; set; }
        public string customer_product_drawer_mand { get; set; }
        public string customer_prod_addition_info_req { get; set; }
        public string customer_prod_addition_info_mand { get; set; }
        public string customer_prod_subcustomer_req { get; set; }
        public string customer_prod_subcustomer_mand { get; set; }
        public string customer_prod_sub_customer_entry_level { get; set; }
        public string customer_product_entered_by { get; set; }
        public Nullable<System.DateTime> customer_product_entered_on { get; set; }
        public string customer_product_authorized_by { get; set; }
        public Nullable<System.DateTime> customer_product_authorized_on { get; set; }
        public string customer_prod_lcc_pickup_req { get; set; }
        public string customer_product_multiple_additional_req { get; set; }
        public string customer_product_pickuppoint_req { get; set; }
        public string custome_product_cash_allowed_in_branches { get; set; }
    }
}
