//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_BankBranchMaster
    {
        public long ID { get; set; }
        public Nullable<int> BANK_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BRANCH_LOCATION_CODE { get; set; }
        public string STATUS_FLAG { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_ON { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public Nullable<System.DateTime> AUTHORIZED_ON { get; set; }
        public Nullable<int> MBRANCH_MICR_CODE { get; set; }
        public string MBRANCH_IS_CBS { get; set; }
    }
}
