//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ProductSuspensionMaster2
    {
        public long ID { get; set; }
        public string SUSREVPX_CUST_CODE { get; set; }
        public string SUSREVPX_PROD_CODE { get; set; }
        public string SUSREVPX_EFF_DATE { get; set; }
        public string SUSREVPX_STAT_FLAG { get; set; }
        public string SUSREVPX_REMARKS1 { get; set; }
        public string SUSREVPX_REMARKS2 { get; set; }
        public string SUSREVPX_REMARKS3 { get; set; }
        public string SUSREVPX_ENTD_BY { get; set; }
        public string SUSREVPX_ENTD_ON { get; set; }
        public string SUSREVPX_AUTH_BY { get; set; }
        public string SUSREVPX_AUTH_ON { get; set; }
        public string SUSREVPX_LAST_MOD_BY { get; set; }
        public string SUSREVPX_LAST_MOD_ON { get; set; }
        public string SUSREVPX_LAST_USED_OPT { get; set; }
        public string SUSREVPX_DAYLOG_KEY { get; set; }
    }
}
