//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxfAcknowledge
    {
        public long Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FileName { get; set; }
        public string ItemSeqNo { get; set; }
        public string PresentingBankRouteNo { get; set; }
        public Nullable<System.DateTime> PresentmentDate { get; set; }
        public Nullable<int> CycleNo { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<int> SessionExtensionHrs { get; set; }
    }
}
