//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public int ID { get; set; }
        public string RoleName { get; set; }
        public bool IsRejectRepaire { get; set; }
        public bool IsDataEntry { get; set; }
        public bool IsQC { get; set; }
        public bool IsVerification { get; set; }
        public bool IsReport { get; set; }
        public bool IsFileDownload { get; set; }
        public bool IsDashboard { get; set; }
        public bool IsQuery { get; set; }
        public bool IsQueryWithModification { get; set; }
        public bool IsReVerification { get; set; }
        public bool IsL4Verification { get; set; }
        public bool IsCCPH_Verification { get; set; }
        public bool IsUserManagement { get; set; }
        public bool IsSOD { get; set; }
        public bool IsMasters { get; set; }
        public bool IsSettings { get; set; }
        public bool IsArchieve { get; set; }
        public bool IsMessageBroadcasting { get; set; }
        public decimal L1StartLimit { get; set; }
        public decimal L1StopLimit { get; set; }
        public decimal L2StartLimit { get; set; }
        public decimal L2StopLimit { get; set; }
        public decimal L3StartLimit { get; set; }
        public decimal L3StopLimit { get; set; }
        public decimal L4StartLimit { get; set; }
        public decimal L4StopLimit { get; set; }
        public bool IsChiReject { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsRoleMaster { get; set; }
        public bool IsUserManagementChecker { get; set; }
        public bool IsRoleMasterChecker { get; set; }
        public int IsActive { get; set; }
    }
}
