//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddList_FILE_UPLOAD_Format_BranchDataEntry
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public string Clearing_Type { get; set; }
        public string File_Format_Name { get; set; }
        public short PresentingMICR_StartIndex { get; set; }
        public short PresentingMICR_Length { get; set; }
        public short DraweeBank_StartIndex { get; set; }
        public short DraweeBank_Length { get; set; }
        public short PresentmentDate_StartIndex { get; set; }
        public short PresentmentDate_Length { get; set; }
        public short Amount_StartIndex { get; set; }
        public short Amount_Length { get; set; }
        public short ChequeNo_StartIndex { get; set; }
        public short ChequeNo_Length { get; set; }
        public Nullable<short> AccountNo_StartIndex { get; set; }
        public Nullable<short> AccountNo_Length { get; set; }
        public short PayeeName_StartIndex { get; set; }
        public short PayeeName_Length { get; set; }
    }
}
