//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearingHouseInterface
    {
        public ClearingHouseInterface()
        {
            this.Banks = new HashSet<Bank>();
        }
    
        public string CC_ROUTING_NBR { get; set; }
        public string NAME { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL_ZIP_CODE { get; set; }
        public string CLEARING_STATUS_CODE { get; set; }
        public string NOTE { get; set; }
        public string ClearingHouse_CH_ROUTING_NBR { get; set; }
    
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual Clearinghouse Clearinghouse { get; set; }
    }
}
