//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainUserMapMaster
    {
        public long ID { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
