//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadedChiFile
    {
        public long Id { get; set; }
        public Nullable<byte> FileType { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string FileName { get; set; }
        public string SourceServer { get; set; }
        public Nullable<System.DateTime> DownloadedDatetime { get; set; }
        public Nullable<System.DateTime> ProcessedDatetime { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> InstrumentCount { get; set; }
    }
}
