//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public int DomainId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> BasicAllowance { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> TRA { get; set; }
        public Nullable<System.DateTime> LastLeaveSalaryPaidOn { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfReJoining { get; set; }
        public Nullable<byte> YearlyLeavesEntilted { get; set; }
        public Nullable<int> NoOfDayEligibleForLeaves { get; set; }
        public Nullable<System.DateTime> LastLeaveTakenFrom { get; set; }
        public Nullable<System.DateTime> LastLeaveTakenTo { get; set; }
        public Nullable<System.DateTime> LastDayWorkedOn { get; set; }
        public Nullable<int> LeavesEligibiltyLeft { get; set; }
        public Nullable<decimal> LeavesEligibleFor { get; set; }
        public Nullable<int> LastLeavesEncashed { get; set; }
        public Nullable<int> CurrentSalaryId { get; set; }
        public Nullable<int> LastSalaryId { get; set; }
        public Nullable<long> TotalDayWorked { get; set; }
        public Nullable<long> TotalAbsent { get; set; }
        public Nullable<long> TotalLeavesTaken { get; set; }
        public Nullable<long> MedicalLeaves { get; set; }
        public Nullable<long> EmegencyLeaves { get; set; }
        public Nullable<long> UnpaidLeaves { get; set; }
        public Nullable<decimal> LeavesEncashed { get; set; }
        public Nullable<decimal> LeavesUnEncashed { get; set; }
        public Nullable<System.DateTime> LastLeavesEncashedOn { get; set; }
        public Nullable<long> CasualLeaves { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
