//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICRLog
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string FrontImage { get; set; }
        public string BackImage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AmountConf { get; set; }
        public string Date { get; set; }
        public Nullable<int> DateConf { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> AccountNoConf { get; set; }
        public Nullable<long> Process_ID { get; set; }
        public string AmountVerification { get; set; }
        public string DateVerification { get; set; }
        public string AccountNoVerification { get; set; }
    }
}
