//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWAmountTmpProcess
    {
        public long ID { get; set; }
        public int OpsStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> EntryAmount { get; set; }
        public Nullable<decimal> ICRAmount { get; set; }
        public Nullable<int> AmountDEBy { get; set; }
        public Nullable<int> AmountQCBy { get; set; }
        public string XMLSerialNo { get; set; }
        public string XMLPayorBankRoutNo { get; set; }
        public string XMLSAN { get; set; }
        public string XMLTransCode { get; set; }
        public string EntryDebtAccountNo { get; set; }
        public string EntrySerialNo { get; set; }
        public string EntryPayorBankRoutNo { get; set; }
        public string EntrySAN { get; set; }
        public string EntryTransCode { get; set; }
        public Nullable<int> DebtAccountNoBy { get; set; }
        public string FrontGreyImagePath { get; set; }
        public string FrontTiffImagePath { get; set; }
        public string BackTiffImagePath { get; set; }
        public string CBSClientAccountDtls { get; set; }
        public string CBSJointHoldersName { get; set; }
        public int File_ID { get; set; }
        public int FileSeqNo { get; set; }
        public string Snippet { get; set; }
        public Nullable<bool> sttsamt { get; set; }
        public string XMLPayeeName { get; set; }
        public string ClearingType { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public string PresentingBankRoutNo { get; set; }
        public string DocType { get; set; }
        public string XMLMICRRepairFlags { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
