//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWFinalMainTransaction
    {
        public long ID { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public int File_ID { get; set; }
        public int FileSeqNo { get; set; }
        public int BatchNo { get; set; }
        public Nullable<int> OpsStatus { get; set; }
        public int MiscStatus { get; set; }
        public string CHIStatus { get; set; }
        public string ItemSeqNo { get; set; }
        public string XMLSerialNo { get; set; }
        public string EntrySerialNo { get; set; }
        public string XMLPayorBankRoutNo { get; set; }
        public string EntryPayorBankRoutNo { get; set; }
        public string XMLSAN { get; set; }
        public string EntrySAN { get; set; }
        public string XMLTransCode { get; set; }
        public string EntryTransCode { get; set; }
        public decimal XMLAmount { get; set; }
        public Nullable<decimal> EntryAmount { get; set; }
        public string XMLPayeeName { get; set; }
        public string EntryPayeeName { get; set; }
        public string ChqDate { get; set; }
        public string DbtAccNo { get; set; }
        public string PresentingBankRoutNo { get; set; }
        public string PresentmentDate { get; set; }
        public string CycleNo { get; set; }
        public string NumOfImageViews { get; set; }
        public string ClearingType { get; set; }
        public string DocType { get; set; }
        public string MICRRepairFlags { get; set; }
        public string SpecialHandling { get; set; }
        public string TruncatingRTNo { get; set; }
        public string IQAIgnoreInd { get; set; }
        public string CurrencyInd { get; set; }
        public string ItemStatus { get; set; }
        public string BOFDRoutNo { get; set; }
        public string BOFDBusDate { get; set; }
        public string DepositorAcct { get; set; }
        public string IFSC { get; set; }
        public string ReturnCode { get; set; }
        public string RRFName { get; set; }
        public Nullable<int> CHIRejectCode { get; set; }
        public string CBSClientAccountDtls { get; set; }
        public string CBSJointHoldersName { get; set; }
        public string FrontTiffImagePath { get; set; }
        public string BackTiffImagePath { get; set; }
        public string FrontGreyImagePath { get; set; }
        public string BackGreyImagePath { get; set; }
        public string UVImagePath { get; set; }
        public string UVStatus { get; set; }
        public string Comments { get; set; }
        public string Remark { get; set; }
        public string ReturnReasonDescription { get; set; }
        public Nullable<int> ReturnMarkedBy_ID { get; set; }
        public string DIN { get; set; }
        public string RECEIVERBRANCHNO { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> RrfUploadTime { get; set; }
        public Nullable<int> ChiFileId { get; set; }
        public Nullable<System.DateTime> RrfCreationDate { get; set; }
        public Nullable<byte> SmbPDFGen { get; set; }
        public Nullable<int> L1By { get; set; }
        public Nullable<int> L1Status { get; set; }
        public Nullable<int> L2By { get; set; }
        public Nullable<int> L2Status { get; set; }
        public Nullable<int> L3By { get; set; }
        public Nullable<int> L3Status { get; set; }
        public Nullable<int> L1RejectReason { get; set; }
        public Nullable<int> L2RejectReason { get; set; }
        public Nullable<int> L3RejectReason { get; set; }
        public string SessionNumber { get; set; }
        public string SessionDate { get; set; }
        public string SettlementDate { get; set; }
        public Nullable<byte> CBSStatus { get; set; }
        public Nullable<byte> PxfGenerationFlag { get; set; }
        public string CPPS_FLAG { get; set; }
        public Nullable<bool> AIACTIVE { get; set; }
        public Nullable<decimal> A2iAAmount { get; set; }
        public string A2iADate { get; set; }
        public string A2iAPayeeName { get; set; }
        public string A2iAMICR { get; set; }
        public string A2iAChequeNo { get; set; }
        public string A2iASortCode { get; set; }
        public string A2iASan { get; set; }
        public string A2iATransCode { get; set; }
        public string A2iADebitAcountNo { get; set; }
        public string A2iADrawersName { get; set; }
        public Nullable<decimal> A2iALARAmount { get; set; }
        public Nullable<decimal> A2iACARAmount { get; set; }
        public Nullable<int> A2iAAmountScore { get; set; }
        public Nullable<int> A2iADateScore { get; set; }
        public Nullable<int> A2iAPayeeNameScore { get; set; }
        public Nullable<int> A2iAMICRScore { get; set; }
        public Nullable<int> A2iADebitAccountNoScore { get; set; }
        public Nullable<int> A2iADrawersNameScore { get; set; }
        public Nullable<int> A2iACARAmountScore { get; set; }
        public Nullable<int> A2iALARAmountScore { get; set; }
        public Nullable<System.DateTime> A2iAProcessedTime { get; set; }
        public Nullable<decimal> A2iAAmount1 { get; set; }
        public string A2iADate1 { get; set; }
        public string A2iAPayeeName1 { get; set; }
        public string A2iAMICR1 { get; set; }
        public string A2iAChequeNo1 { get; set; }
        public string A2iASortCode1 { get; set; }
        public string A2iASan1 { get; set; }
        public string A2iATransCode1 { get; set; }
        public string A2iADebitAcountNo1 { get; set; }
        public string A2iADrawersName1 { get; set; }
        public Nullable<decimal> A2iALARAmount1 { get; set; }
        public Nullable<decimal> A2iACARAmount1 { get; set; }
        public Nullable<int> A2iAAmountScore1 { get; set; }
        public Nullable<int> A2iADateScore1 { get; set; }
        public Nullable<int> A2iAPayeeNameScore1 { get; set; }
        public Nullable<int> A2iAMICRScore1 { get; set; }
        public Nullable<int> A2iADebitAccountNoScore1 { get; set; }
        public Nullable<int> A2iADrawersNameScore1 { get; set; }
        public Nullable<int> A2iACARAmountScore1 { get; set; }
        public Nullable<int> A2iALARAmountScore1 { get; set; }
        public Nullable<System.DateTime> A2iAProcessedTime1 { get; set; }
    }
}
