//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWMICRTmpProcess
    {
        public long ID { get; set; }
        public Nullable<int> OpsStatus { get; set; }
        public decimal XMLAmount { get; set; }
        public string XMLSerialNo { get; set; }
        public string EntrySerialNo { get; set; }
        public string SerialNoOCR1 { get; set; }
        public string SerialNoOCR2 { get; set; }
        public string XMLPayorBankRoutNo { get; set; }
        public string PayorBankRoutNoOCR1 { get; set; }
        public string PayorBankRoutNoOCR2 { get; set; }
        public string XMLSAN { get; set; }
        public string EntrySAN { get; set; }
        public string SANOCR1 { get; set; }
        public string SANOCR2 { get; set; }
        public string XMLTransCode { get; set; }
        public string EntryTransCode { get; set; }
        public string TransCodeOCR1 { get; set; }
        public string TransCodeOCR2 { get; set; }
        public string MICRRepairFlags { get; set; }
        public Nullable<int> MICRDEBy { get; set; }
        public Nullable<int> MICRQCBy { get; set; }
        public string FrontGreyImagePath { get; set; }
        public string FrontTiffImagePath { get; set; }
        public string BackTiffImagePath { get; set; }
        public string Snippet { get; set; }
        public Nullable<bool> sttsdtqc { get; set; }
        public int File_ID { get; set; }
        public int FileSeqNo { get; set; }
        public string XMLPayeeName { get; set; }
        public string ClearingType { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public string PresentingBankRoutNo { get; set; }
        public string DocType { get; set; }
        public string XMLMICRRepairFlags { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> A2iAAmount { get; set; }
        public string A2iADate { get; set; }
        public string A2iAPayeeName { get; set; }
        public string A2iAMICR { get; set; }
        public string A2iAChequeNo { get; set; }
        public string A2iASortCode { get; set; }
        public string A2iASan { get; set; }
        public string A2iATransCode { get; set; }
        public string A2iADebitAcountNo { get; set; }
        public string A2iADrawersName { get; set; }
        public Nullable<decimal> A2iALARAmount { get; set; }
        public Nullable<decimal> A2iACARAmount { get; set; }
        public Nullable<int> A2iAAmountScore { get; set; }
        public Nullable<int> A2iADateScore { get; set; }
        public Nullable<int> A2iAPayeeNameScore { get; set; }
        public Nullable<int> A2iAMICRScore { get; set; }
        public Nullable<int> A2iADebitAccountNoScore { get; set; }
        public Nullable<int> A2iADrawersNameScore { get; set; }
        public Nullable<int> A2iACARAmountScore { get; set; }
        public Nullable<int> A2iALARAmountScore { get; set; }
        public Nullable<System.DateTime> A2iAProcessedTime { get; set; }
        public Nullable<bool> AIACTIVE { get; set; }
        public Nullable<decimal> A2iAAmount1 { get; set; }
        public string A2iADate1 { get; set; }
        public string A2iAPayeeName1 { get; set; }
        public string A2iAMICR1 { get; set; }
        public string A2iAChequeNo1 { get; set; }
        public string A2iASortCode1 { get; set; }
        public string A2iASan1 { get; set; }
        public string A2iATransCode1 { get; set; }
        public string A2iADebitAcountNo1 { get; set; }
        public string A2iADrawersName1 { get; set; }
        public Nullable<decimal> A2iALARAmount1 { get; set; }
        public Nullable<decimal> A2iACARAmount1 { get; set; }
        public Nullable<int> A2iAAmountScore1 { get; set; }
        public Nullable<int> A2iADateScore1 { get; set; }
        public Nullable<int> A2iAPayeeNameScore1 { get; set; }
        public Nullable<int> A2iAMICRScore1 { get; set; }
        public Nullable<int> A2iADebitAccountNoScore1 { get; set; }
        public Nullable<int> A2iADrawersNameScore1 { get; set; }
        public Nullable<int> A2iACARAmountScore1 { get; set; }
        public Nullable<int> A2iALARAmountScore1 { get; set; }
        public Nullable<System.DateTime> A2iAProcessedTime1 { get; set; }
        public Nullable<bool> AIACTIVE1 { get; set; }
    }
}
