//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int ID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailID { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int InvalidPasswordAttempts { get; set; }
        public bool UserDeleted { get; set; }
        public int loginFlg { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string sessionid { get; set; }
        public bool FirstLogin { get; set; }
        public int AppSecPolicieID { get; set; }
        public Nullable<int> ModifedBy { get; set; }
        public string City { get; set; }
        public decimal L1StartLimit { get; set; }
        public decimal L1StopLimit { get; set; }
        public decimal L2StartLimit { get; set; }
        public decimal L2StopLimit { get; set; }
        public decimal L3StartLimit { get; set; }
        public decimal L3StopLimit { get; set; }
        public string UsertType { get; set; }
        public Nullable<bool> AllDomain { get; set; }
        public string ClientCode { get; set; }
        public string AccessLevel { get; set; }
        public Nullable<decimal> L4StartLimit { get; set; }
        public Nullable<decimal> L4StopLimit { get; set; }
        public string VendorCode { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
