//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikloud_Aflatoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMasterActivity
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Action { get; set; }
        public Nullable<int> ActionBy { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> Actiondate { get; set; }
    }
}
